### ISSUE TITLE
（杠精维基人来了）可以瞒过杀毒软件[谁?]的病毒[来源请求]

### ISSUE THREAD

**Issue by Misaka-0x447f** [CasterWx/c-cPlusPlus-Virus#1]
（我来抬杠了不要理我）
杀毒软件的反病毒原理基本如下:
1.由用户提交病毒样本或自动发现可疑病毒样本，跟踪病毒特征码/特征行为
2.启发式发现病毒，同样是分析病毒行为
那么这款明显不具备自我变异功能的病毒怎样在投放后瞒过杀毒软件呢？又是瞒过哪款杀毒软件呢？
另外在不显示用户界面的情况下是如何骗过带有启发式杀毒功能的杀毒软件呢？
还有一类特殊的杀毒软件的反病毒原理如下：
3.白名单杀毒，不认识的统统杀掉，没签名的更是一个不留
（典型案例：avast打开严格模式，某年的360）
这个病毒又是如何骗过安全实验室的工作人员的呢？

**Comment by CasterWx** [comment]
> （我来抬杠了不要理我）
> 杀毒软件的反病毒原理基本如下:
> 1.由用户提交病毒样本或自动发现可疑病毒样本，跟踪病毒特征码/特征行为
> 2.启发式发现病毒，同样是分析病毒行为
> 那么这款明显不具备自我变异功能的病毒怎样在投放后瞒过杀毒软件呢？又是瞒过哪款杀毒软件呢？
> 另外在不显示用户界面的情况下是如何骗过带有启发式杀毒功能的杀毒软件呢？
> 还有一类特殊的杀毒软件的反病毒原理如下：
> 3.白名单杀毒，不认识的统统杀掉，没签名的更是一个不留
> （典型案例：avast打开严格模式，某年的360）
> 这个病毒又是如何骗过安全实验室的工作人员的呢？

hhhhhhhhh，看了你的博客站点，太可爱了
